type GreetingResponse {
	greeting: String!
}

type UpdateGreetingResponse {
	greeting: String!
}

type Query {
	greeting(name: String!): GreetingResponse!
}

type Mutation {
	updateGreeting(greeting: String!): UpdateGreetingResponse!
}